; Hermes 学而思 ESP32版 (hermes-xrs)
; ESP32 + SPI TFT + MicroSD + 6 Keys + Buzzer + Sensors
; 与 hermes-t5 功能完全相同

[env:hermes-xrs]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

; Partition table
board_build.partitions = huge_app.csv

; Build flags
build_flags = 
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160
  -DTFT_DRIVER=ST7735

; Libraries
lib_deps = 
  bodmer/TFT_eSPI@^2.5.43
